#!/usr/bin/env python3
"""Generate the bridge-load-planning data set (not shipped).

Builds a fleet of 14 tractor/53-ft trailer units. Six can only run with the trailer
tandem slid forward (kingpin-to-rear-axle limits at their destinations), which puts the
drive-tandem-to-trailer-tandem span at 35.5-37 ft: those units are only near full
capacity when the 34k+34k two-tandem exception (and half-up foot rounding) is applied.
Three units are weaker (short spans, heavier tare). Pallets are generated by first
building a hidden 11-truck plan that is legal, so the minimum is known to be achievable;
the weight lower bound proves 11 is also necessary.
"""
import csv
import random
import shutil
import sys
from fractions import Fraction as F
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] / "tasks" / "bridge-load-planning"
sys.path.insert(0, str(ROOT / "solution"))
import solve  # noqa: E402

ENV = ROOT / "environment" / "data"
TST = ROOT / "tests" / "data"
NUSED = 9  # units in the minimum plan

TRACTORS = {  # steer, drive1, drive2 in the trailer frame (kingpin at 36 in)
    "SLP-230": (-182, 22, 74),
    "DAY-204": (-160, 18, 70),
    "SLP-254": (-200, 28, 80),
}
TARE = {"SLP-230": (11200, 4700, 4700), "DAY-204": (10600, 4500, 4500), "SLP-254": (11600, 4800, 4800)}

DENSE = [  # description, weight range (lb), lengths (in)
    ("steel coil on cradle", (9000, 16000), [48, 60]),
    ("cast iron fittings", (3500, 6000), [40, 48]),
    ("paper rolls", (3000, 4500), [48]),
]
BULKY = [
    ("machinery skid", (6000, 12000), [96, 120, 144]),
    ("transformer crate", (3500, 7000), [120, 144, 168]),
    ("beverage pallet", (2100, 2600), [48]),
]


# Idle-reduction units: (certified weight lb, certified fully functional)
APU = {
    "U01": (612, True), "U02": (585, False), "U03": (640, True), "U04": (560, True),
    "U05": (598, True), "U06": (471, True), "U07": (623, True), "U08": (566, True),
    "U09": (604, True), "U10": (590, True), "U11": (575, True),
}


def unit_rows():
    rng = random.Random(658)
    units, sliders = [], []

    def add(uid, tractor, t1s, trailer_tare=(3800, 3800)):
        s, d1, d2 = TRACTORS[tractor]
        cert, functional = APU.get(uid, (None, None))
        units.append(dict(unit_id=uid, tractor_model=tractor, steer_x_in=s, drive1_x_in=d1, drive2_x_in=d2,
                          kingpin_x_in=36, trailer_inside_length_in=630,
                          apu_installed="yes" if cert else "no",
                          apu_certified_weight_lb=cert or "",
                          apu_fully_functional=("yes" if functional else "no") if cert else ""))
        for n, t1 in enumerate(t1s, 1):
            ts, td1, td2 = TARE[tractor]
            sliders.append(dict(unit_id=uid, slider_position_id=f"{uid}-S{n}", trailer1_x_in=t1, trailer2_x_in=t1 + 50,
                                tare_steer_lb=ts, tare_drive1_lb=td1, tare_drive2_lb=td2,
                                tare_trailer1_lb=trailer_tare[0], tare_trailer2_lb=trailer_tare[1]))

    # long-rail units: full slider rail
    add("U01", "SLP-230", [416, 524])
    add("U02", "SLP-254", [416, 524])
    add("U03", "DAY-204", [428, 500])
    # forward-only units, drive-to-trailer tandem span 35.5 - 37 ft (need the 34k+34k allowance)
    add("U04", "SLP-230", [398])            # 426 in = 35.5 ft, rounds to 36
    add("U05", "SLP-254", [392, 404])       # 414 in (34.5 ft) / 426 in (35.5 ft)
    add("U06", "SLP-230", [380, 404])       # 408 in (34 ft) / 432 in (36 ft)
    add("U07", "DAY-204", [388, 410])       # 420 in (35 ft) / 442 in (36.8 ft)
    # short-rail units, span under 35.5 ft: the axle 2-5 group binds
    add("U08", "DAY-204", [380, 392])       # 412 / 424 in
    add("U09", "SLP-254", [372, 384])       # 394 / 406 in
    # weak units: short rail and heavier trailers
    add("U10", "SLP-230", [368], (4200, 4200))
    add("U11", "DAY-204", [356, 374], (4400, 4400))
    del rng
    return units, sliders


def write_csv(path, rows):
    with open(path, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]), lineterminator="\n")
        w.writeheader()
        w.writerows(rows)


def best_config(cfgs):
    return max(((solve.capacity(c), c) for c in cfgs), key=lambda t: (t[0], t[1].slider_id))


def shortcut_bestN(limit_fn=None, allowance_fn=None):
    orig_b, orig_a = solve.bridge_limit, solve.apu_allowance
    solve.bridge_limit = limit_fn or orig_b
    solve.apu_allowance = allowance_fn or orig_a
    try:
        configs, _ = solve.load_problem()
        caps = sorted((best_config(c)[0] for c in configs.values()), reverse=True)
    finally:
        solve.bridge_limit, solve.apu_allowance = orig_b, orig_a
    return sum(caps[:NUSED])


def cfr_400(unit):  # the stale regulation amount
    if unit.get("apu_installed") != "yes" or unit.get("apu_fully_functional") != "yes":
        return 0
    return min(int(unit["apu_certified_weight_lb"]), 400)


def floor_feet_limit(span, n, two_tandems):
    feet = span // 12
    w = 500 * solve.half_up((F(feet * n, n - 1) + 12 * n + 36))
    if two_tandems and feet >= 36:
        w = max(w, 68000)
    return w


def main():
    units, sliders = unit_rows()
    ENV.mkdir(parents=True, exist_ok=True)
    write_csv(ENV / "units.csv", units)
    write_csv(ENV / "sliders.csv", sliders)
    solve.DATA = ENV
    write_csv(ENV / "pallets.csv", [dict(pallet_id="P000", description="x", weight_lb=1, length_in=48)])
    configs, _ = solve.load_problem()
    caps = sorted(((best_config(c) + (u,)) for u, c in configs.items()), key=lambda t: -t[0])
    chosen = caps[:NUSED]
    rng = random.Random(16)
    trueN = sum(c[0] for c in chosen)
    true_limit = solve.bridge_limit
    worst = max(shortcut_bestN(lambda sp, n, t: true_limit(sp, n, False)),
                shortcut_bestN(floor_feet_limit),
                shortcut_bestN(allowance_fn=lambda u: 0),
                shortcut_bestN(allowance_fn=cfr_400))
    total_target = worst + 200     # just above what any under-applying rule can carry on N units
    assert total_target > worst, "shortcut rules must need an extra truck"
    slack = trueN - total_target
    cuts = sorted(rng.sample(range(1, slack), NUSED - 1))
    slacks = [b - a for a, b in zip([0] + cuts, cuts + [slack])]
    print("trueN", trueN, "shortcutN", worst, "target", total_target)
    pallets = []
    hidden = []
    for (cap, cfg_best, uid), sl in zip(chosen, slacks):
        long_rail = uid in ("U01", "U02", "U03")
        if long_rail:
            # rearmost slider setting that still has the unit's full capacity
            cfg = max((c for c in configs[uid] if solve.capacity(c) == cap), key=lambda c: c.x[3])
        else:
            cfg = cfg_best
        target = cap - sl
        for attempt in range(20000):
            n = rng.randint(4, 6)
            kinds = [rng.choice(DENSE + BULKY[:1]) for _ in range(n)]
            lens = [rng.choice(k[2]) for k in kinds]
            if sum(lens) > 560:
                continue
            raw = [rng.uniform(*k[1]) for k in kinds]
            ws = [int(round(r * target / sum(raw) / 5)) * 5 for r in raw]
            ws[-1] += target - sum(ws)
            if not all(1500 <= w <= 16500 and w <= 320 * ln for w, ln in zip(ws, lens)):
                continue
            items = [(f"x{i}", w, ln) for i, (w, ln) in enumerate(zip(ws, lens))]
            plan = solve.solve_plan([cfg], items, 1, 5)
            if isinstance(plan, list) and plan:
                pallets += [(k[0], w, ln) for k, w, ln in zip(kinds, ws, lens)]
                hidden.append((uid, cfg.slider_id, sum(lens), target))
                break
        else:
            raise SystemExit(f"could not fill {uid}")
    for h in hidden:
        print("hidden", h)
    rng.shuffle(pallets)
    rows = [dict(pallet_id=f"P{i:03d}", description=d, weight_lb=w, length_in=ln)
            for i, (d, w, ln) in enumerate(pallets, 1)]
    write_csv(ENV / "pallets.csv", rows)
    TST.mkdir(parents=True, exist_ok=True)
    for f in ENV.glob("*.csv"):
        shutil.copy(f, TST / f.name)
    total = sum(p[1] for p in pallets)
    print("pallets", len(pallets), "total", total, "best-12", sum(c[0] for c in chosen),
          "best-(N-1)", sum(c[0] for c in caps[:NUSED - 1]))
    (ROOT / "tests" / "expected.json").write_text('{"min_units": %d}\n' % len(chosen))
    for c in caps:
        print(c[2], c[1].slider_id, c[0])


if __name__ == "__main__":
    main()
